<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Article_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get article by article_id
     */
    function list_article($type, $offset, $article_id=0)
    {
        $limit = 3;
        $this->db->select('a.*, u.usr_fullname as created_user');
            $this->db->join('users u','a.created_by = u.usr_id','left');             
            $this->db->where("a.type_article = ".$type);                     
            $this->db->where("a.status_review = 1");
            if($article_id != 0){
                $this->db->where("a.article_id != ".$article_id);
            }

            $this->db->order_by("a.created_at", 'DESC');
      
            $query = $this->db->get('article a', $limit, $offset);
            if($query->num_rows() > 0){
                return $query->result();
            }else{
                return false;
            }
    }    
}
