<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Donasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by usr_id
     */
    function get_donasi()
    {
        $donasi = $this->db->query("
            SELECT
                *

            FROM
                `donasi`

            WHERE
                `donasi_id` = 1

        ")->row();

        return $donasi;
    }    
    
    function update_donasi($params)
    {
        $this->db->where('donasi_id',1);
        return $this->db->update('donasi',$params);
    }  
}
