<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by usr_id
     */
    function get_user($usr_id)
    {
        $user = $this->db->query("
            SELECT
                u.*, g.gro_name

            FROM
                `users` u
            LEFT JOIN groups g
            on u.usr_group = g.gro_id

            WHERE
                `usr_id` = ?

        ",array($usr_id))->row_array();

        return $user;
    }

        
    /*
     * Get all users
     */
    function get_all_users()
    {
        $users = $this->db->query("
            SELECT
                *

            FROM
                `users`

            ORDER BY `usr_id` DESC
        ")->result_array();

        return $users;
    }
    function get_forgot_users()
    {
        $users = $this->db->query("
            SELECT
                *

            FROM
                `users`

            WHERE
                 is_reset  = 1

            ORDER BY `usr_id` DESC
        ")->result_array();

        return $users;
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($usr_id,$params)
    {
        $this->db->where('usr_id',$usr_id);
        return $this->db->update('users',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($usr_id)
    {
        return $this->db->delete('users',array('usr_id'=>$usr_id));
    }
}
