<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Donasi extends CI_Controller{
    function __construct()
    {
        parent::__construct();        
        $this->load->model('Donasi_model');   
        $this->load->model('general_model');          
    } 

    /*
     * Listing of users
     */
    public function index()
	{			
        $this->user_library->checking_page_access('donasi',"donasi","view");   
        $data['donasi'] = $this->Donasi_model->get_donasi();				
        $where_kontak['organization_id'] = 1;                   
        $data['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            
		$this->load->view('backend/donasi/view_donasi',$data);
	}

	public function edit()
	{			
        $this->user_library->checking_page_access('donasi',"donasi","edit");   
        $data['donasi'] = $this->Donasi_model->get_donasi();	
        $where_kontak['organization_id'] = 1;                   
        $data['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            			
		$this->load->view('backend/donasi/edit_donasi',$data);
	}

	public function doedit()
	{	        
        $this->user_library->checking_page_access('donasi',"donasi","edit");   
		date_default_timezone_set('Asia/Jakarta');		
		if(isset($_POST) && count($_POST) > 0){   			
            $params = array(
                'description' => $this->input->post('description'),   
                'updated_by' => $this->session->userdata('user_id'),             
                'updated_at' => date('Y-m-d H:i:s'),                 
            );            
            $this->Donasi_model->update_donasi($params);            
            $this->session->set_flashdata('success','Edit Donasi Success');                
            redirect('admin/donasi/');
        }
        else{
          $this->session->set_flashdata('error','There are no post from previous action');
          redirect('admin/donasi/edit_donasi');
        }
	}
    
}
