<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Iklan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        // if($this->session->userdata('group') !=  '1')
        // {
        //     $this->session->set_flashdata('error','You have no access to that page.');
        //     redirect('login');  
        // }
        $this->load->model('User_model');
        $this->load->model('general_model');
        $this->load->model('user_group_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {        
        $this->user_library->checking_page_access('ads',"ads","view");           
        
        $data['iklan'] = $this->general_model->get_info("*", "ads");
        $where_kontak['organization_id'] = 1;                   
        $data['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            
        $this->load->view('backend/iklan/master_iklan',$data);
    }
    
    function add()
    {   
        $this->user_library->checking_page_access('ads',"ads","add");   
        date_default_timezone_set('Asia/Jakarta');		

        $where_kontak['organization_id'] = 1;                   
        $data['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            

        if(isset($_POST) && count($_POST) > 0)     
        {               
        $where_iklan['ads_position'] = $this->input->post("posisi_iklan");  
    $check_iklan = $this->general_model->get_info("count(1) as count", "ads", $where_iklan);                
    
    if($check_iklan != FALSE) {        
        if($check_iklan->row()->count > 0){            
            $posisi_name = "Home";

            if($this->input->post("posisi_iklan") == 2){
                $posisi_name = "Berita";
            }else if($this->input->post("posisi_iklan") == 3){
                $posisi_name = "Artikel";
            }else if($this->input->post("posisi_iklan") == 4){
                $posisi_name = "Serba - Serbi";
            }

            $this->session->set_flashdata('error', 'Posisi Iklan dipage '.$posisi_name.' Sudah terisi');
            return redirect("admin/iklan");
        }               
    }

    $this->load->library('upload');

            $params = array(												
				'ads_position' => $this->input->post('posisi_iklan'),				
                'created_by' => $this->session->userdata('user_id'),             
                'created_at' => date('Y-m-d H:i:s'),                                	
            );         
            
            if(isset($_FILES['logo'])){
                $logo = $_FILES['logo']['name'];   
                if($logo != null){
                    $series_name = 'adsfull-'.$this->input->post('posisi_iklan').'-'.date('dmYHis');
                    $config['upload_path']          = './assets/images/tmp/';
                $config['allowed_types']        = 'gif|jpg|png|tiff|pjp|pjpeg|jfif|tif|svg|bmp|jpeg|svgz|webp|ico|xbm|dib';            
                $config['max_size']             = 0;// = MB
                $config['max_width']            = 2000;
                $config['max_height']           = 2000;		
                $config['file_name'] 			= $series_name; 
    
                if ($this->upload->initialize($config) && ! $this->upload->do_upload('logo'))
                {   
                    $this->session->set_flashdata('error',$this->upload->display_errors());  
                    return $this->load->view('backend/iklan/add_iklan', $data);										              															
                }else{					
                    $upload_image = $this->upload->data();	
    
                    $this->load->library('Compress');
                    $compress0 = new Compress();		
            
            $compress0->file_url = getcwd().'/assets/images/tmp/'.$upload_image['file_name'];
            $compress0->new_name_image = $upload_image['file_name'];
            $compress0->quality = 60;
            $compress0->destination = base_url().'assets/images/ads/';
    
            $compress0->compress_image();
            
            if(file_exists(getcwd().'/assets/images/tmp/'.$upload_image['file_name'])){
                unlink(getcwd().'/assets/images/tmp/'.$upload_image['file_name']);						
            }		
                    $params['url_full'] = $upload_image['file_name'];
                }												
                }
            }

            if(isset($_FILES['logo']) && $this->input->post('isImage') == 1){
                $logo = $_FILES['logo']['name'];   
                if($logo != null && $this->input->post('isImage') == 1){
                    $params['url'] = $params['url_full'];
                }
            }else if($this->input->post('isImage') == 0 && $this->input->post('imageBase64') != ""){
                $dataImage = $this->input->post('imageBase64');
    
                list($type, $dataImage) = explode(';', $dataImage);
            list(, $dataImage)      = explode(',', $dataImage);
         
            $dataImage = base64_decode($dataImage);
            $imageName = 'ads-'.$this->input->post('posisi_iklan').'-'.date('dmYHis').'.png';            

            file_put_contents('assets/images/tmp/'.$imageName, $dataImage);

        $this->load->library('Compress');
        $compress0 = new Compress();		

$compress0->file_url = getcwd().'/assets/images/tmp/'.$imageName;
$compress0->new_name_image = $imageName;
$compress0->quality = 60;
$compress0->destination = base_url().'assets/images/ads/';

$compress0->compress_image();

if(file_exists(getcwd().'/assets/images/tmp/'.$imageName)){
    unlink(getcwd().'/assets/images/tmp/'.$imageName);						
}
    
            $params['url'] = $imageName;
            
            }

            $this->db->trans_start();

            $this->db->insert('ads',$params);

            $this->db->trans_complete();
                        
            $this->session->set_flashdata('success','Add Iklan Success');    
            redirect('admin/iklan');

        }
        else
        {            
            $data['iklan'] = $this->general_model->get_info("*", "ads")->result();            
            $this->load->view('backend/iklan/add_iklan', $data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($iklan_id)
    {   
        $this->user_library->checking_page_access('ads',"ads","edit");   
        date_default_timezone_set('Asia/Jakarta');
        
        $where_organization['organization_id'] = 1;    		            

		$data['kontak'] = $this->general_model->get_info("*", "organization", $where_organization)->row();        		
		
        $where_iklan['ads_id'] = $iklan_id;   
        $data['iklan'] = $this->general_model->get_info("*", "ads", $where_iklan);
        
        if($data['iklan'] != FALSE)
        {        
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $where_iklan_position['ads_position'] = $this->input->post("posisi_iklan");  
                $exception_iklan['field'] = 'ads_id';
        $exception_iklan['value'] = $iklan_id;
    $check_iklan = $this->general_model->get_info("count(1) as count", "ads", $where_iklan_position,
    array(), array(), $exception_iklan);                            
    
    if($check_iklan != FALSE) {        
        if($check_iklan->row()->count > 0){            
            $posisi_name = "Home";

            if($this->input->post("posisi_iklan") == 2){
                $posisi_name = "Berita";
            }else if($this->input->post("posisi_iklan") == 3){
                $posisi_name = "Artikel";
            }else if($this->input->post("posisi_iklan") == 4){
                $posisi_name = "Serba - Serbi";
            }

            $this->session->set_flashdata('error', 'Posisi Iklan dipage '.$posisi_name.' Sudah terisi');
            return redirect("admin/iklan");
        }               
    }

    $this->load->library('upload');

    $deleteFile = array();

            $params = array(												
				'ads_position' => $this->input->post('posisi_iklan'),				
                'updated_by' => $this->session->userdata('user_id'),             
                'updated_at' => date('Y-m-d H:i:s'),                                	
            );         
            
            if(isset($_FILES['logo'])){
                $logo = $_FILES['logo']['name'];   
                if($logo != null){
                    $series_name = 'adsfull-'.$this->input->post('posisi_iklan').'-'.date('dmYHis');
                    $config['upload_path']          = './assets/images/tmp/';
                $config['allowed_types']        = 'gif|jpg|png|tiff|pjp|pjpeg|jfif|tif|svg|bmp|jpeg|svgz|webp|ico|xbm|dib';            
                $config['max_size']             = 0;// = MB
                $config['max_width']            = 2000;
                $config['max_height']           = 2000;		
                $config['file_name'] 			= $series_name; 
    
                if ($this->upload->initialize($config) && ! $this->upload->do_upload('logo'))
                {   
                    $this->session->set_flashdata('error',$this->upload->display_errors());  
                    return $this->load->view('backend/iklan/add_iklan', $data);										              															
                }else{					
                    $upload_image = $this->upload->data();	
    
                    $this->load->library('Compress');
                    $compress0 = new Compress();		
            
            $compress0->file_url = getcwd().'/assets/images/tmp/'.$upload_image['file_name'];
            $compress0->new_name_image = $upload_image['file_name'];
            $compress0->quality = 60;
            $compress0->destination = base_url().'assets/images/ads/';
    
            $compress0->compress_image();
            
            if(file_exists(getcwd().'/assets/images/tmp/'.$upload_image['file_name'])){
                unlink(getcwd().'/assets/images/tmp/'.$upload_image['file_name']);						
            }		
                    $params['url_full'] = $upload_image['file_name'];

                    array_push($deleteFile, $data['iklan']->row()->url_full);
                }												
                }
            }

            if(isset($_FILES['logo']) && $this->input->post('isImage') == 1){
                $logo = $_FILES['logo']['name'];   
                if($logo != null && $this->input->post('isImage') == 1){
                    $params['url'] = $params['url_full'];
                    array_push($deleteFile, $data['iklan']->row()->url);
                }
            }else if($this->input->post('isImage') == 0 && $this->input->post('imageBase64') != ""){
                $dataImage = $this->input->post('imageBase64');
    
                list($type, $dataImage) = explode(';', $dataImage);
            list(, $dataImage)      = explode(',', $dataImage);
         
            $dataImage = base64_decode($dataImage);
            $imageName = 'ads-'.$this->input->post('posisi_iklan').'-'.date('dmYHis').'.png';            

            file_put_contents('assets/images/tmp/'.$imageName, $dataImage);

        $this->load->library('Compress');
        $compress0 = new Compress();		

$compress0->file_url = getcwd().'/assets/images/tmp/'.$imageName;
$compress0->new_name_image = $imageName;
$compress0->quality = 60;
$compress0->destination = base_url().'assets/images/ads/';

$compress0->compress_image();

if(file_exists(getcwd().'/assets/images/tmp/'.$imageName)){
    unlink(getcwd().'/assets/images/tmp/'.$imageName);						
}
    
            $params['url'] = $imageName;

            if($data['iklan']->row()->url != $data['iklan']->row()->url_full){
                array_push($deleteFile, $data['iklan']->row()->url);
            }                            
            
            }

            $this->db->trans_start();

            $this->db->update('ads',$params,$where_iklan);

            $this->db->trans_complete();

            if(count($deleteFile) > 0){
                foreach($deleteFile as $delete){
                    if(file_exists(getcwd().'/assets/images/ads/'.$delete)){
                        unlink(getcwd().'/assets/images/ads/'.$delete);						
                    }		
                }
            }            
                        
            $this->session->set_flashdata('success','Edit Iklan Success');    
            redirect('admin/iklan');
            }
            else
            {                                
                $this->load->view('backend/iklan/edit_iklan',$data);
            }
        }
        else {
            $this->session->set_flashdata('error','Iklan doesnt exist');    
            redirect('admin/iklan');
        }        
    } 

    /*
     * Deleting user
     */
    function remove($ads_id)
    {        
        $this->user_library->checking_page_access('ads',"ads","delete");   
        $where_ads['ads_id'] = $ads_id;               
        $check_ads = $this->general_model->get_info("url, url_full", "ads", $where_ads);                            
        
        if($check_ads != FALSE)
        {
            $this->db->delete('ads',array('ads_id'=>$ads_id));

            if(file_exists(getcwd().'/assets/images/ads/'.$check_ads->row()->url)) {
                unlink(getcwd().'/assets/images/ads/'.$check_ads->row()->url);
            }

            if(file_exists(getcwd().'/assets/images/ads/'.$check_ads->row()->url_full)) {
                unlink(getcwd().'/assets/images/ads/'.$check_ads->row()->url_full);
            }

            $this->session->set_flashdata('success','Delete Iklan Success');                
            redirect('admin/iklan');
        }
        else {
            $this->session->set_flashdata('error','Delete Iklan Failed');    
            redirect('admin/iklan');
        }            
    }

    public function View($id){
        $this->user_library->checking_page_access('ads',"ads","view");           
        $where_iklan['ads_id'] = $id;   
        $data['iklan'] = $this->general_model->get_info("*", "ads", $where_iklan);
        $where_kontak['organization_id'] = 1;                   
        $data['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            

        if($data['iklan'] != FALSE)
        {
            $this->load->view('backend/iklan/view_iklan',$data);
        }else{
            $this->session->set_flashdata('error','Iklan doesnt exist');    
            redirect('admin/iklan');
        }		
	}
    
}
