<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_group extends CI_Controller{
    function __construct()
    {
        parent::__construct();                
        $this->load->model('user_group_model');
        $this->load->model('general_model');     
    } 

    /*
     * Listing of category
     */
    function index()
    {
        $this->user_library->checking_page_access('user_group',"user_group","view");   
        $data['user_group'] = $this->user_group_model->get_all_user_group();
        $where_kontak['organization_id'] = 1;                   
        $data['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            
        $this->load->view('backend/user_group/master_usergroup',$data);
    }

    /*
     * Adding a new category
     */
    function add()
    {   
        $this->user_library->checking_page_access('user_group',"user_group","add");   
        if(isset($_POST) && count($_POST) > 0)     
        {               

        $name = $this->input->post('user_group_name');        
        $article = $this->input->post('articles');
        $user = $this->input->post('users');
        $user_group = $this->input->post('user_groups');
        $donasi = $this->input->post('donations');
        $contact = $this->input->post('contacts');
        $ads = $this->input->post('ads');        
        
        $this->form_validation->set_rules('user_group_name', 'name', 'callback_check_name');        
        
            $this->db->trans_start();

            $data['gro_name'] = $name;
            if($article != "" && $article != null && count($article) > 0){
                $article_format = "";
                $index = 0;
                if(is_array($article)){
                    foreach($article as $key => $value){
                        if($index == 0){
                            $article_format.=";";
                        }
                        $article_format.=$value.";";
                        $index++;
                    }
                }else{
                    $article_format = ";".$article.";";
                }
                $data['article_all_access'] = $article_format;
            }
            if($user != "" && $user != null && count($user) > 0){
                $user_access_format = "";
                $index = 0;
                if(is_array($user)){
                    foreach($user as $key => $value){
                        if($index == 0){
                            $user_access_format.=";";
                        }
                        $user_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $user_access_format = ";".$user.";";
                }
                $data['user_all_access'] = $user_access_format;
            }
            if($user_group != "" && $user_group != null && count($user_group) > 0){
                $user_group_access_format = "";
                $index = 0;
                if(is_array($user_group)){
                    foreach($user_group as $key => $value){
                        if($index == 0){
                            $user_group_access_format.=";";
                        }
                        $user_group_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $user_group_access_format = ";".$user_group.";";
                }
                $data['user_group_all_access'] = $user_group_access_format;
            }
            if($donasi != "" && $donasi != null && count($donasi) > 0){
                $donasi_access_format = "";
                $index = 0;
                if(is_array($donasi)){
                    foreach($donasi as $key => $value){
                        if($index == 0){
                            $donasi_access_format.=";";
                        }
                        $donasi_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $donasi_access_format = ";".$donasi.";";
                }
                $data['donasi_all_access'] = $donasi_access_format;
            }
            if($contact != "" && $contact != null && count($contact) > 0){
                $contact_access_format = "";
                $index = 0;
                if(is_array($contact)){
                    foreach($contact as $key => $value){
                        if($index == 0){
                            $contact_access_format.=";";
                        }
                        $contact_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $contact_access_format = ";".$contact.";";
                }
                $data['contact_all_access'] = $contact_access_format;
            }
            if($ads != "" && $ads != null && count($ads) > 0){
                $ads_access_format = "";
                $index = 0;
                if(is_array($ads)){
                    foreach($ads as $key => $value){
                        if($index == 0){
                            $ads_access_format.=";";
                        }
                        $ads_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $ads_access_format = ";".$ads.";";
                }
                $data['ads_all_access'] = $ads_access_format;
            }            

            $this->db->insert('groups',$data);            
            $this->db->trans_complete();

            $this->session->set_flashdata('success','Add User Group Success');                         
            redirect('admin/user_group');        
        }
        else
        {            
            $where_kontak['organization_id'] = 1;                   
        $data['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            
            $this->load->view('backend/user_group/add_usergroup', $data);
        }
    }  

    /*
     * Editing a category
     */
    function edit($group_id)
    {   
        $this->user_library->checking_page_access('user_group',"user_group","edit");   
        // check if the category exists before trying to edit it
        if($group_id == 1) {
            $this->session->set_flashdata('error', "Maaf Anda Tidak Dapat Mengubah Group Admin !");
            redirect('admin/user_group');
        }
        $data_by_id['user_group'] = $this->user_group_model->get_user_group($group_id);
        $data_by_id['user'] = explode(';', $data_by_id['user_group']['user_all_access']);
        $data_by_id['user_group_access'] = explode(';', $data_by_id['user_group']['user_group_all_access']);
        $data_by_id['donasi'] = explode(';', $data_by_id['user_group']['donasi_all_access']);
        $data_by_id['contact'] = explode(';', $data_by_id['user_group']['contact_all_access']);
        $data_by_id['article'] = explode(';', $data_by_id['user_group']['article_all_access']);
        $data_by_id['ads'] = explode(';', $data_by_id['user_group']['ads_all_access']);        

        $where_kontak['organization_id'] = 1;                   
        $data_by_id['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            
                
        if(isset($data_by_id['user_group']['gro_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {                   
        $name = $this->input->post('user_group_name');        
        $article = $this->input->post('articles');
        $user = $this->input->post('users');
        $user_group = $this->input->post('user_groups');
        $donasi = $this->input->post('donations');
        $contact = $this->input->post('contacts');
        $ads = $this->input->post('ads');        
                                 
            $this->db->trans_start();

            $data['gro_name'] = $name;
            if($article != "" && $article != null && count($article) > 0){
                $article_format = "";
                $index = 0;
                if(is_array($article)){
                    foreach($article as $key => $value){
                        if($index == 0){
                            $article_format.=";";
                        }
                        $article_format.=$value.";";
                        $index++;
                    }
                }else{
                    $article_format = ";".$article.";";
                }
                $data['article_all_access'] = $article_format;
            }else{
                $data['article_all_access'] = null;
            }

            if($user != "" && $user != null && count($user) > 0){
                $user_access_format = "";
                $index = 0;
                if(is_array($user)){
                    foreach($user as $key => $value){
                        if($index == 0){
                            $user_access_format.=";";
                        }
                        $user_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $user_access_format = ";".$user.";";
                }                                
                $data['user_all_access'] = $user_access_format;
            }else{
                $data['user_all_access'] = null;
            }

            if($user_group != "" && $user_group != null && count($user_group) > 0){
                $user_group_access_format = "";
                $index = 0;
                if(is_array($user_group)){
                    foreach($user_group as $key => $value){
                        if($index == 0){
                            $user_group_access_format.=";";
                        }
                        $user_group_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $user_group_access_format = ";".$user_group.";";
                }
                $data['user_group_all_access'] = $user_group_access_format;
            }else{
                $data['user_group_all_access'] = null;
            }

            if($donasi != "" && $donasi != null && count($donasi) > 0){
                $donasi_access_format = "";
                $index = 0;
                if(is_array($donasi)){
                    foreach($donasi as $key => $value){
                        if($index == 0){
                            $donasi_access_format.=";";
                        }
                        $donasi_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $donasi_access_format = ";".$donasi.";";
                }
                $data['donasi_all_access'] = $donasi_access_format;
            }else{
                $data['donasi_all_access'] = null;
            }

            if($contact != "" && $contact != null && count($contact) > 0){
                $contact_access_format = "";
                $index = 0;
                if(is_array($contact)){
                    foreach($contact as $key => $value){
                        if($index == 0){
                            $contact_access_format.=";";
                        }
                        $contact_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $contact_access_format = ";".$contact.";";
                }
                $data['contact_all_access'] = $contact_access_format;
            }else{
                $data['contact_all_access'] = null;
            }

            if($ads != "" && $ads != null && count($ads) > 0){
                $ads_access_format = "";
                $index = 0;
                if(is_array($ads)){
                    foreach($ads as $key => $value){
                        if($index == 0){
                            $ads_access_format.=";";
                        }
                        $ads_access_format.=$value.";";
                        $index++;
                    }
                }else{
                    $ads_access_format = ";".$ads.";";
                }
                $data['ads_all_access'] = $ads_access_format;
            }else{
                $data['ads_all_access'] = null;
            }
            
            $where['gro_id'] = $group_id;

            $this->db->update('groups',$data,$where);   
            $this->user_library->reset_login_info();         
            $this->db->trans_complete();          
                        
            $this->session->set_flashdata('success','Update User Group Success');                         
            redirect('admin/user_group/index');        
            }
            else
            {                        
                $this->load->view('backend/user_group/edit_usergroup',$data_by_id);
            }
        }
        else {
            $this->session->set_flashdata('error','The User Group you are trying to Edit does not exist.');                                
        redirect('admin/user_group/');
        }        
    } 

    public function View($id){
        $this->user_library->checking_page_access('user_group',"user_group","view");   
        $data_by_id['user_group'] = $this->user_group_model->get_user_group($id);
        $data_by_id['user'] = explode(';', $data_by_id['user_group']['user_all_access']);
        $data_by_id['user_group_access'] = explode(';', $data_by_id['user_group']['user_group_all_access']);
        $data_by_id['donasi'] = explode(';', $data_by_id['user_group']['donasi_all_access']);
        $data_by_id['contact'] = explode(';', $data_by_id['user_group']['contact_all_access']);
        $data_by_id['article'] = explode(';', $data_by_id['user_group']['article_all_access']);
        $data_by_id['ads'] = explode(';', $data_by_id['user_group']['ads_all_access']);        

        $where_kontak['organization_id'] = 1;                   
        $data_by_id['kontak'] = $this->general_model->get_info("*", "organization", $where_kontak)->row();                            

        if(isset($data_by_id['user_group']['gro_id']))
        {
            $this->load->view('backend/user_group/view_usergroup',$data_by_id);
        }else{
            $this->session->set_flashdata('error','User Group doesnt exist');    
            redirect('admin/user_group');
        }		
	}

    /*
     * Deleting category
     */
    function remove($group_id)
    {
        $this->user_library->checking_page_access('user_group',"user_group","delete");   
        $user_group = $this->user_group_model->get_user_group($group_id);

        // check if the category exists before trying to delete it
        if(isset($user_group['gro_id']))
        {
            $check_group = $this->user_group_model->check_user_group($group_id);                        
            if($check_group > 0){                                
                $this->session->set_flashdata('error','The User Group still use by the User');                                
                redirect('admin/user_group/');
            }                        
            $this->user_group_model->delete_user_group($group_id);
            $this->session->set_flashdata('success','Delete User Group Success'); 
            redirect('admin/user_group/');
        }
        else            
            $this->session->set_flashdata('error','The User Group you are trying to delete does not exist.');                                
                redirect('admin/user_group/');
    }    
}
